#!/bin/bash
if [ "$1" = "--help" ]; then
	echo -e "this is to \e[1;31m r\e[0me\e[1;31mn\e[0mew a script.
u have to write it like : rn >filename<.
if it isnt working u have chosen the wrong name.
press >enter< to quit"
	read -r
	exit 1
else
	if [ -f "$1" ]; then
		echo "u will be helped"
		if [ -f "/bin/$1" ]; then
			echo "this file already exists. do u wanna overwrite
(y/n)"
			read response
			if [ "$response" = "y" ]; then
				mv "$1" /bin/"$1"
				chmod a+x /bin/"$1"
				exit 1
			else
				if [ "$response" = "n" ]; then
					echo "u wanna create a new file (y/n)"
					read response
					if [ "$response" = "y" ]; then
						echo -n "insert name [$filename] > "
						read response
						if [ -n "$response" ]; then
							mv "$1" "$response"
							mv "$response" /bin/"$response"
							chmod a+x /bin/"$response"
							exit 1
						fi
					else
						echo "u dont want to overwrite? ok
press >enter< to quit"
						read -r
						exit 1
					fi
				else
					echo "u dont want to overwrite? ok
press >enter< to quit"
					read -r
					exit 1
				fi
			fi
		else
			mv "$1" /bin/"$1"
			chmod a+x /bin/"$1"
			exit 1

		fi
	else
		echo "dis impossibru. try --help.
press >enter< to quit"
		read -r
		exit 1
	fi
fi
