#!/bin/bash
if [ "$1" = "--help" ]; then
	echo -e "this is to \e[1;31m r\e[0me\e[1;31mn\e[0mew a script.
u have to write it like : rn >filename< >bin or sbin<
if it isnt working u have chosen the wrong filename or directory.
press >enter< to quit"
	read -r
	exit 1
else
	if [ "$2" = "bin" ] || [ "$2" = "sbin" ]; then
		if [ -f "$1" ]; then
			echo "u will be helped"
			if [ -f "/$2/$1" ]; then
				echo "this file already exists. do u wanna overwrite
(y/n)"
				read response
				if [ "$response" = "y" ]; then
					mv "$1" /"$2"/"$1"
					chmod a+x /"$2"/"$1"
					exit 1
				else
					if [ "$response" = "n" ]; then
						echo "u wanna create a new file (y/n)"
						read response
						if [ "$response" = "y" ]; then
							echo -n "insert name [$filename] > "
							read response
							if [ -n "$response" ]; then
								mv "$1" "$response"
								mv "$response" /"$2"/"$response"
								chmod a+x /"$2"/"$response"
								exit 1
							fi
						else
							echo "u dont want to create? ok
press >enter< to quit"
							read -r
							exit 1
						fi
					else
						echo "u dont want to overwrite? ok
press >enter< to quit"
						read -r
						exit 1
					fi
				fi
			else
				mv "$1" /"$2"/"$1"
				chmod a+x /"$2"/"$1"
				exit 1

			fi
		else
			echo "dis impossibru. try --help.
press >enter< to quit"
			read -r
			exit 1
		fi
	else
		echo "dis is impossibru. try --help.
press >enter< to quit"
		read -r
		exit 1
	fi
fi
